# Generated by Django 3.0.8 on 2021-01-06 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210106_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='user_type',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
