# Generated by Django 3.0.8 on 2021-01-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcategories_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='user_type',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Children', 'Children'), ('Unisex', 'Unisex')], max_length=20),
        ),
    ]
